# Generated by Django 5.2.4 on 2025-08-04 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('USER_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NAME', models.TextField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('GENDER', models.CharField()),
                ('PASSWORD', models.TextField()),
                ('AGE', models.IntegerField()),
                ('GYM_LOCATION', models.TextField(null=True)),
                ('HOME_LOCATION', models.TextField(null=True)),
            ],
        ),
    ]
