# Generated by Django 5.2.4 on 2025-08-04 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('USER_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NAME', models.TextField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('GENDER', models.CharField()),
                ('PASSWORD', models.TextField()),
                ('AGE', models.PositiveIntegerField()),
                ('GYM_LOCATION', models.TextField(null=True)),
                ('HOME_LOCATION', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRACK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='WORKOUTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXERCISE_ID', models.TextField(blank=True, null=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.CreateModel(
            name='SETTING',
            fields=[
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('is_darkmode', models.BooleanField(default=True)),
            ],
        ),
    ]
