# Generated by Django 5.2.4 on 2025-08-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_track_workouts_delete_users_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
