# Generated by Django 5.2.4 on 2025-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_setting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='ID',
            new_name='USER_ID',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='ID',
            new_name='USER_ID',
        ),
        migrations.RenameField(
            model_name='workouts',
            old_name='ID',
            new_name='USER_ID',
        ),
        migrations.AddField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
